# Generated by Django 2.0.4 on 2018-04-25 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20180425_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default='Xiaomi', max_length=64, verbose_name='Производитель'),
            preserve_default=False,
        ),
    ]
