# Generated by Django 2.0.4 on 2018-04-25 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(default='noname', max_length=64, verbose_name='Производитель'),
        ),
    ]
